# Generated by Django 4.1.2 on 2023-08-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0002_authtokentoken_authuser_users_login_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
