# Generated by Django 4.1.2 on 2023-11-06 15:41

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0003_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_link',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='files',
            name='file_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(default=' ', max_length=5),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='fileflow'), upload_to=django_minio_backend.models.iso_date_prefix),
        ),
    ]
